#
#
# 
FROM node:18-buster-slim
LABEL maintainer="Filippo Bergamasco <filippo.bergamasco@unive.it>"

EXPOSE 4200

WORKDIR /app
COPY postmessagesweb /app
RUN npm install -g @angular/cli
#RUN npm install

